### ISSUE TITLE
"Not enough ingredients" on Industrial Fermenter appears across maps

### ISSUE THREAD

**Issue by skairunner** [PeladorRW/Fermenter#1]
Situation: I have built some Industrial Fermenters set to produce beer from wort in my settlement Hops. I then switch to my original settlement, Dream.

Expected: I don't see anything out of the norm.

Actual: I get phantom icons where the fermenters would be in Dream.

![image](https://user-images.githubusercontent.com/3517115/75093972-0b538880-55ca-11ea-97c1-c95b25927262.png)
Dream. Notice the three "not enough wort" icons next to the artillery.

![image](https://user-images.githubusercontent.com/3517115/75093982-20301c00-55ca-11ea-8144-7400a250195b.png)
Hops. The fermenters want more wort.

**Comment by PeladorRW** [comment]
Now applied a fix in V1.1, tyvm

If I get time, as priorities allow, I will do the same for V1.0

**Comment by skairunner** [comment]
I heard that it's possible to support both 1.0 and 1.1 on the same codebase, is that not feasible? I'm reluctant to move off 1.0 until all my mods are updated, and it's a pretty hefty list of mods.

**Comment by PeladorRW** [comment]
It is possible but chose a KISS Engineering approach with my updates. This since I only intend to support the latest version of RW as version control moves forward.

Also with RW changing this then can lead to extra bloat with files (mod size) where differences exist between versions, and that in itself adds complexity dependant on what Ludeon change.

With the move from V1 to V1.1 there has been a change in the .net, unity and harmony versions anyhow so, alternative assemblies would be required regardless, where I would be concerned about having backwards compatibility. That coupled with the already observed complications seen from Ludeon's implementation with this new version control model.

The older versions will remain on Github and Steam (as their own mods).
